### ISSUE TITLE
[Issue] Vercelのビルドにて `SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON` によりデプロイできない

### ISSUE THREAD

**Issue by wiyco** [iputapp/lounas#308]
# Issue

Dev. 🐧

## Overview of Issue

Vercel上でのビルドでこけるためデプロイできない。

## Details

ブランチ `chore/package-update` : `next@14.2.5`
```
[00:26:01.985] Running build in Washington, D.C., USA (East) – iad1
[00:26:02.528] Cloning github.com/iputapp/lounas (Branch: chore/package-update, Commit: 6e87e3b)
[00:26:02.557] Skipping build cache, deployment was triggered without cache.
[00:26:03.420] Cloning completed: 889.749ms
[00:26:03.421] Ignore Build Step was explicitly skipped for this deployment.
[00:26:04.081] Running "vercel build"
[00:26:05.070] Vercel CLI 35.1.0
[00:26:06.078] Installing dependencies...
~
[00:26:38.002] Running "npm run build"
[00:26:38.387] 
[00:26:38.387] > lounas@0.2.1 build
[00:26:38.387] > prisma generate && next build
~
[00:26:40.952]   ▲ Next.js 14.2.5
[00:26:40.953] 
[00:26:41.028]    Creating an optimized production build ...
~
[00:27:33.301]  ✓ Compiled successfully
[00:27:33.302]    Linting and checking validity of types ...
[00:27:47.597]    Collecting page data ...
[00:27:48.584] SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
[00:27:48.584]     at JSON.parse (<anonymous>)
[00:27:48.584]     at parseJSONFromBytes (node:internal/deps/undici/undici:4306:19)
[00:27:48.584]     at successSteps (node:internal/deps/undici/undici:4288:27)
[00:27:48.584]     at fullyReadBody (node:internal/deps/undici/undici:2724:9)
[00:27:48.584]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[00:27:48.584]     at async consumeBody (node:internal/deps/undici/undici:4297:7)
[00:27:48.584]     at async Object.M [as generateStaticParams] (/vercel/path0/.next/server/app/(pages)/dish/[id]/page.js:4:2918)
[00:27:48.585]     at async buildParams (/vercel/path0/node_modules/next/dist/build/utils.js:1026:40)
[00:27:48.585]     at async /vercel/path0/node_modules/next/dist/build/utils.js:1043:33
[00:27:48.585]     at async /vercel/path0/node_modules/next/dist/build/utils.js:1177:114
[00:27:48.587] 
[00:27:48.587] > Build error occurred
[00:27:48.590] Error: Failed to collect page data for /dish/[id]
[00:27:48.599]     at /vercel/path0/node_modules/next/dist/build/utils.js:1268:15
[00:27:48.599]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
[00:27:48.599]   type: 'Error'
[00:27:48.599] }
[00:27:48.687] Error: Command "npm run build" exited with 1
```

`next@14.2.4`: Revert commit 6596d4487b033895bb1b2170dfc5f67d290a30ee
正常にVercel上でビルドできていた[commit](a5bd729a2355368a97729feea8acdbee26dc5f7a)にrevertしたが同様のエラーが出る。
```
[23:58:20.302] Running build in Washington, D.C., USA (East) – iad1
[23:58:20.492] Cloning github.com/iputapp/lounas (Branch: develop, Commit: 6596d44)
[23:58:21.490] Cloning completed: 996.183ms
[23:58:21.490] Running "bash vercel-build-ignore.sh"
[23:58:21.587] 🚀 Starting build for branch develop
[23:58:21.618] ✅ Proceeding with the build
[23:58:30.090] Restored build cache
[23:58:30.304] Running "vercel build"
[23:58:31.417] Vercel CLI 35.1.0
[23:58:32.164] Installing dependencies...
~
[23:58:36.367] Running "npm run build"
[23:58:36.905] 
[23:58:36.905] > lounas@0.2.0 build
[23:58:36.905] > prisma generate && next build
~
[23:58:39.841]   ▲ Next.js 14.2.4
[23:58:39.842] 
[23:58:39.913]    Creating an optimized production build ...
[23:58:48.277]  ✓ Compiled successfully
[23:58:48.279]    Linting and checking validity of types ...
[23:58:55.679]    Collecting page data ...
[23:58:56.504] SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
[23:58:56.505]     at JSON.parse (<anonymous>)
[23:58:56.505]     at parseJSONFromBytes (node:internal/deps/undici/undici:4306:19)
[23:58:56.505]     at successSteps (node:internal/deps/undici/undici:4288:27)
[23:58:56.505]     at fullyReadBody (node:internal/deps/undici/undici:2724:9)
[23:58:56.505]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[23:58:56.505]     at async consumeBody (node:internal/deps/undici/undici:4297:7)
[23:58:56.505]     at async Object.M [as generateStaticParams] (/vercel/path0/.next/server/app/(pages)/dish/[id]/page.js:4:2918)
[23:58:56.505]     at async buildParams (/vercel/path0/node_modules/next/dist/build/utils.js:1026:40)
[23:58:56.505]     at async /vercel/path0/node_modules/next/dist/build/utils.js:1043:33
[23:58:56.505]     at async /vercel/path0/node_modules/next/dist/build/utils.js:1177:114
[23:58:56.510] 
[23:58:56.510] > Build error occurred
[23:58:56.513] Error: Failed to collect page data for /dish/[id]
[23:58:56.513]     at /vercel/path0/node_modules/next/dist/build/utils.js:1268:15
[23:58:56.513]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
[23:58:56.513]   type: 'Error'
[23:58:56.513] }
[23:58:56.576] Error: Command "npm run build" exited with 1
```

## Remark

同様の報告がないか[Vercelのissue](https://github.com/vercel/vercel/issues)を漁ったが見つからず。

## Before submitting

> [!WARNING]
>
> The following is allowed for review only. (No additions or modifications are permitted.)

- [x] I agree to the [Code of Conduct](https://github.com/iputapp/lounas/blob/develop/.github/CODE_OF_CONDUCT.md).

**Comment by wiyco** [comment]
# 原因調査

おそらく、原因は Vercel CLI のバージョンアップグレードによるものだと思われる。

Vercel上のビルドログから以下が確認できている。

- Build OK:  `Vercel CLI 34.2.8`
- Build NG: `Vercel CLI 35.1.0`
